#!/bin/bash
#
# XIV failed component monitoring
#
# Matvey Marinin 2014
#
# Must be run as zabbix user
# Arguments:
# $1 - XIV DNS name/IP address
#
# Requirements:
#   - Oracle/Sun JRE (jre-7u55-linux-x64.rpm)
#   - XCLI (xivGUI-4.3.1-build1-linux64.bin)
#   - run "/opt/ibm/xiv/xcli --protect" as zabbix user to save XIV credentials
#
# 06.08.2014 v2 - fixed xcli error handling
#
set -e

XIV_RESULT="$(/opt/ibm/xiv/xcli -m "$1" component_service_required_list)"
echo "$XIV_RESULT" | tail -n+2 | awk '{print $1, $2}'
