#!/bin/bash
#
# XIV monitoring script for Zabbix
#
# 2014 Matvey Marinin
#
# Use with "_Special_XIV" Zabbix template
# 
# 1) Define LLD rule "XIV Volume pools" with external item xiv_mon["{HOST.HOST}","{HOST.CONN}","discovery"]
# 2) Define prototype trapper items with keys:
#     xiv.pool.hard_size[{#ID}]
#     xiv1 xiv.pool.hard_size.left[{#ID}]
#     xiv.pool.hard_size.pct[{#ID}]
#     xiv.pool.hard_size[{#ID}]
#     xiv.pool.hard_size.left[{#ID}]
#     xiv.pool.hard_size.pct[{#ID}]
#     xiv.pool.total_hard_size
#     xiv.pool.total_hard_size_left
#     xiv.pool.total_hard_size_pct
#
# 3) Define LLD rule "XIV Snapshot pools" with external item xiv_mon["{HOST.HOST}","{HOST.CONN}","snap_discovery"]
# 4) Define prototype trapper items with keys:
#     xiv.pool.snap.space_left[{#ID}]
#     xiv.pool.snap.space_pctleft[{#ID}]
#
# 5) Define ordinary item "xiv_mon_getdata" with external check xiv_mon["{HOST.HOST}","{HOST.CONN}","data"]. It used to poll data
#
# Usage:
#   xiv_mon <xiv_host> <xiv_mgmt_interface> <mode>
#
#   $1 = XIV host name in Zabbix
#   $2 = XIV management interface DNS name or IP address
#   $3 = operation mode <discovery|snap_discovery|data>
#

set -e

. /etc/zabbix/externalscripts/xiv_mon.conf

ERR_LOG=/var/log/zabbix/xiv_mon

PYTHON=/usr/bin/python

START_TIME=$(date)

echo "$1" "$2" "$3" "Started: $START_TIME" >> "$ERR_LOG"

if [[ $3 == 'discovery' ]]; then
  "$PYTHON" /etc/zabbix/externalscripts/xiv_mon.py "$1" "$2" "$XIV_USER" "$XIV_PWD" discovery 2>>"$ERR_LOG"
fi

if [[ $3 == 'snap_discovery' ]]; then
  "$PYTHON" /etc/zabbix/externalscripts/xiv_mon.py "$1" "$2" "$XIV_USER" "$XIV_PWD" snap_discovery 2>>"$ERR_LOG"
fi

if [[ $3 == 'data' ]]; then
  "$PYTHON" /etc/zabbix/externalscripts/xiv_mon.py "$1" "$2" "$XIV_USER" "$XIV_PWD" data 2>>"$ERR_LOG" | zabbix_sender -z 127.0.0.1 -I 127.0.0.1 -T -i - >>"$ERR_LOG" 2>&1
  echo $?
fi

echo "$1" "$2" "$3" "Finished: $START_TIME" - $(date) >> "$ERR_LOG"
